import { v4 as uuid } from "uuid";
const homeMetrics = [
  {
    value: "+2 Md GNF",
    description: "Mobilisés à ce jour",
  },
  {
    value: "6",
    description: "Projets actifs en 2026",
  },
  {
    value: "100%",
    description: "Investisseurs satisfaits",
  },
  {
    value: "1,5 M",
    description: "Diaspora à mobiliser",
  },
];
const homeMissions = [
  {
    icon: "🤝",
    title: "GUINUTY Participatif",
    description:
      "Crowdlending de proximité pour PME, écoles et infrastructures de quartier.",
  },
  {
    icon: "🌍",
    title: "GUINUTY Diaspora",
    description: "Investir au pays simplement, sans intermédiaire opaque.",
  },
  {
    icon: "🏗️",
    title: "GUINUTY Projets",
    description: "Co-financement de projets structurants avec les bailleurs.",
  },
  {
    icon: "⚡",
    title: "Fast Finance",
    description:
      "Prêts courts adossés à des créances solides, rendement attractif.",
  },
];
const projects = [
  {
    category: "Éducation",
    title: "École Les Champions",
    smallDesc:
      "Agrandissement des salles de classe d'un établissement franco-guinéen de référence.",
    collected: 744000000,
    goal: 1200000000,
    duration: 32,
    efficiency: 31,
  },
  {
    category: "Immobilier",
    title: "OFICI by Toogueda",
    smallDesc:
      "Espace de coworking premium à Kipé Dadia, adossé à des contrats ENABEL.",
    collected: 480000000,
    goal: 1000000000,
    duration: 13,
    efficiency: 35,
  },
  {
    category: "Tech / Santé",
    title: "Brainsense",
    smallDesc:
      "Solution numérique de santé cognitive, portée par une équipe guinéenne.",
    collected: 170000000,
    goal: 500000000,
    duration: 3,
    efficiency: 10,
  },
  {
    category: "Industrie",
    title: "Capstone",
    smallDesc: "Unité de transformation agroalimentaire à Coyah.",
    collected: 355000000,
    goal: 500000000,
    duration: 30,
    efficiency: 15,
  },
  {
    category: "Commerce",
    title: "SM Guinée",
    smallDesc: "Extension d'un réseau de distribution de proximité.",
    collected: 130000000,
    goal: 500000000,
    duration: 18,
    efficiency: 16,
  },
  {
    category: "Agriculture",
    title: "SSakhima",
    smallDesc: "Projet agricole d'irrigation et de maraîchage en Basse-Guinée.",
    collected: 275000000,
    goal: 500000000,
    duration: 36,
    efficiency: 14,
  },
];
const projectCategories = [
  {
    name: "Éducation",
    icon: "🎓",
    bgColor: "#E8F7F5",
  },
  {
    name: "Immobilier",
    icon: "🏢",
    bgColor: "#FDF6E3",
  },
  {
    name: "Tech / Santé",
    icon: "🧠",
    bgColor: "#EAF3DE",
  },
  {
    name: "Industrie",
    icon: "🏭",
    bgColor: "#E8F7F5",
  },
  {
    name: "Commerce",
    icon: "🛒",
    bgColor: "#FDF6E3",
  },
  {
    name: "Agriculture",
    icon: "🌾",
    bgColor: "#EAF3DE",
  },
];
const missions = [
  {
    icon: "🌱",
    title: "Impact local",
    description:
      "Chaque euro investi reste en Guinée et finance un projet réel",

    bgColor: "dark-subtle",
  },
  {
    icon: "🔒",
    title: "Sécurité",
    description: "Fonds cantonnés. KYC obligatoire. 0% de défaut à ce jour",

    bgColor: "info-subtle",
  },
  {
    icon: "🤝",
    title: "Communauté",
    description:
      "Investisseurs locaux, diaspora, et porteurs réunis sur une plateforme",

    bgColor: "warning-subtle",
  },
  {
    icon: "⚡",
    title: "Transparence",
    description: "Suivi en temps réel. Rapports détaillés. Aucune boîte noire",
    bgColor: "success-subtle",
  },
];
const qualities = [
  {
    icon: "🔍",
    title: "Transparence",
    description:
      "Aucune boîte noire. Tous les chiffres, toutes les décisions, toutes les erreurs — publiés.",

    bgColor: "transparent",
  },
  {
    icon: "⚖️",
    title: "Rigueur",
    description:
      "Chaque projet est analysé avec la même exigence. Aucun compromis sur la qualité de sélection.",

    bgColor: "transparent",
  },
  {
    icon: "🌱",
    title: "Impact",
    description:
      "Nous mesurons notre succès à la réussite des projets que nous finançons, pas à nos commissions.",

    bgColor: "transparent",
  },
  {
    icon: "🤝",
    title: "Confiance",
    description:
      "La confiance se gagne par des preuves répétées. Chaque remboursement honoré est un jalon.",
    bgColor: "transparent",
  },
];
const metrics = [
  {
    value: "+2 Md GNF",
    description: "Mobilisés à ce jour",
  },
  {
    value: "6",
    description: "Projets actifs en 2026",
  },
  {
    value: "100%",
    description: "Investisseurs satisfaits",
  },
  {
    value: "1,5 M",
    description: "Diaspora à mobiliser",
  },
];
const investorSteps = [
  {
    icon: "💡",
    title: "Crée ton compte",
    description:
      "Inscription en 3 minutes. KYC simple. Validation par notre équipe sous 24h.",
    step: 1,
    bgColor: "dark-subtle",
  },
  {
    icon: "🔍",
    title: "Explore",
    description:
      "Parcours facilement les projets vérifiés par notre équipe chaque jour.",
    step: 2,
    bgColor: "info-subtle",
  },
  {
    icon: "🔒",
    title: "Investis",
    description:
      "À partir de 50 000 GNF. Tes fonds sont cantonnés dans un compte.",
    step: 3,
    bgColor: "warning-subtle",
  },
  {
    icon: "💰",
    title: "Reçois",
    description:
      "Mensualités automatiques. Suivi facile et rapide sur ton dashboard.",
    step: 4,
    bgColor: "success-subtle",
  },
];
const entrepreneurSteps = [
  {
    icon: "📋",
    title: "Soumission",
    description: "Décris ton projet, ton besoin, tes garanties.",
    step: 1,
    bgColor: "dark-subtle",
  },
  {
    icon: "🔎",
    title: "Analyse",
    description: "Sous 7 jours avec un feedback détaillé.",
    step: 2,
    bgColor: "info-subtle",
  },
  {
    icon: "✅",
    title: "Validation",
    description: "Approbation finale et rapide par la direction.",
    step: 3,
    bgColor: "warning-subtle",
  },
  {
    icon: "📡",
    title: "Campagne",
    description: "Ton projet est visible par toute la communauté. ",
    step: 4,
    bgColor: "success-subtle",
  },
];
const faqs = [
  {
    text: "Quel est le montant minimum pour investir ?",
    answer:
      "À partir de 50 000 GNF pour un prêt participatif. Il n'y a pas de maximum.",
    id: uuid(),
  },
  {
    text: "Comment GUINUTY se rémunère-t-il ?",
    answer:
      "GUINUTY perçoit une commission de 8% sur les montants levés, prélevée directement sur les fonds collectés. Aucune commission n'est facturée aux investisseurs.",
    id: uuid(),
  },
  {
    text: "Que se passe-t-il si un porteur ne rembourse pas ?",
    answer:
      "GUINUTY active un processus de recouvrement en qualité de mandataire des investisseurs. Mise en demeure, restructuration amiable, puis procédure judiciaire si nécessaire. Notre taux de défaut à ce jour est de 0%.",
    id: uuid(),
  },
  {
    text: "Mes fonds sont-ils sécurisés ?",
    answer:
      "Oui. Tous les fonds sont cantonnés dans un compte bancaire ségrégué, séparé du patrimoine de GUINUTY SAS. Ils ne peuvent être utilisés qu'aux fins de l'opération concernée.",
    id: uuid(),
  },
  {
    text: "Comment sont sélectionnés les projets ?",
    answer:
      "Chaque projet passe par une analyse interne (score /10), une vérification KYC du porteur, et une validation finale par le CEO ou le CFO de GUINUTY. Seuls les projets avec un score ≥ 5/10 sont publiés.",
    id: uuid(),
  },
  {
    text: "Puis-je vendre mes parts avant la fin du terme ?",
    answer:
      "Les investissements en prêt participatif ne sont pas cessibles. Les titres en equity peuvent être cédés sous conditions du Pacte d'Actionnaires.",
    id: uuid(),
  },
];
const project = {
  category: "Éducation",
  title: "École Les Champions",
  smallDesc:
    "Agrandissement des salles de classNamee d'un établissement franco-guinéen de référence.",
  collected: 744000000,
  goal: 1200000000,
  duration: 32,
  efficiency: 31,
  investors: 128,
  remainingDays: "18j",
  remainingParts: 850,
  leaveCapital: "20%",
  investmentType: "equity",
  keyPoints: [
    {
      value: "Modèle éprouvé depuis 2013",
      description:
        "12 ans d'activité continue, croissance régulière du chiffre d'affaires.",
    },
    {
      value: "CAF de 1,28 Md GNF/an",
      description: "Couvre 2,5 fois le service de la dette projeté.",
    },
    {
      value: "Endettement net négatif",
      description: "Plus de trésorerie que de dettes, gestion saine.",
    },
    {
      value: "Garanties solides",
      description: "Nantissement du fonds, hypothèque et caution personnelle.",
    },
  ],
  deadlines: [
    {
      period: "Tranche 1 — à 12 mois",
      amount: "420 M GNF",
      status: "À venir",
    },
    {
      period: "Tranche 2 — à 24 mois",
      amount: "400 M GNF",
      status: "À venir",
    },
    {
      period: "Tranche 3 — à 36 mois",
      amount: "380 M GNF",
      status: "À venir",
    },
  ],
};
const nationalities = [
  { value: "afghane", label: "Afghane" },
  { value: "albanaise", label: "Albanaise" },
  { value: "algerienne", label: "Algérienne" },
  { value: "allemande", label: "Allemande" },
  { value: "americaine", label: "Américaine" },
  { value: "andorrane", label: "Andorrane" },
  { value: "angolaise", label: "Angolaise" },
  { value: "antiguaise-et-barbudienne", label: "Antiguaise-et-Barbudienne" },
  { value: "saoudienne", label: "Saoudienne" },
  { value: "argentine", label: "Argentine" },
  { value: "armenienne", label: "Arménienne" },
  { value: "australienne", label: "Australienne" },
  { value: "autrichienne", label: "Autrichienne" },
  { value: "azerbaidjanaise", label: "Azerbaïdjanaise" },
  { value: "bahamienne", label: "Bahamienne" },
  { value: "bahreinienne", label: "Bahreïnienne" },
  { value: "bangladaise", label: "Bangladaise" },
  { value: "barbadienne", label: "Barbadienne" },
  { value: "belge", label: "Belge" },
  { value: "belizienne", label: "Bélizienne" },
  { value: "beninoise", label: "Béninoise" },
  { value: "bhoutanaise", label: "Bhoutanaise" },
  { value: "bielorusse", label: "Biélorusse" },
  { value: "birmane", label: "Birmane" },
  { value: "bolivienne", label: "Bolivienne" },
  { value: "bosnienne", label: "Bosnienne" },
  { value: "botswanaise", label: "Botswanaise" },
  { value: "bresilienne", label: "Brésilienne" },
  { value: "bruneienne", label: "Brunéienne" },
  { value: "bulgare", label: "Bulgare" },
  { value: "burkinabe", label: "Burkinabè" },
  { value: "burundaise", label: "Burundaise" },
  { value: "cambodgienne", label: "Cambodgienne" },
  { value: "camerounaise", label: "Camerounaise" },
  { value: "canadienne", label: "Canadienne" },
  { value: "cap-verdienne", label: "Cap-Verdienne" },
  { value: "centrafricaine", label: "Centrafricaine" },
  { value: "chilienne", label: "Chilienne" },
  { value: "chinoise", label: "Chinoise" },
  { value: "chypriote", label: "Chypriote" },
  { value: "colombienne", label: "Colombienne" },
  { value: "comorienne", label: "Comorienne" },
  { value: "congolaise", label: "Congolaise" },
  { value: "nord-coreenne", label: "Nord-Coréenne" },
  { value: "sud-coreenne", label: "Sud-Coréenne" },
  { value: "costaricienne", label: "Costaricienne" },
  { value: "ivoirienne", label: "Ivoirienne" },
  { value: "croate", label: "Croate" },
  { value: "cubaine", label: "Cubaine" },
  { value: "danoise", label: "Danoise" },
  { value: "djiboutienne", label: "Djiboutienne" },
  { value: "dominicaine", label: "Dominicaine" },
  { value: "egyptienne", label: "Égyptienne" },
  { value: "emirienne", label: "Émirienne" },
  { value: "equatorienne", label: "Équatorienne" },
  { value: "erythreenne", label: "Érythréenne" },
  { value: "espagnole", label: "Espagnole" },
  { value: "estonienne", label: "Estonienne" },
  { value: "ethiopienne", label: "Éthiopienne" },
  { value: "fidjienne", label: "Fidjienne" },
  { value: "finlandaise", label: "Finlandaise" },
  { value: "francaise", label: "Française" },
  { value: "gabonaise", label: "Gabonaise" },
  { value: "gambienne", label: "Gambienne" },
  { value: "georgienne", label: "Géorgienne" },
  { value: "ghanaenne", label: "Ghanéenne" },
  { value: "grecque", label: "Grecque" },
  { value: "grenadienne", label: "Grenadienne" },
  { value: "guatemalteque", label: "Guatémaltèque" },
  { value: "guineenne", label: "Guinéenne" },
  { value: "bissau-guineenne", label: "Bissau-Guinéenne" },
  { value: "equato-guineenne", label: "Équato-Guinéenne" },
  { value: "guyanienne", label: "Guyanienne" },
  { value: "haitienne", label: "Haïtienne" },
  { value: "hondurienne", label: "Hondurienne" },
  { value: "hongroise", label: "Hongroise" },
  { value: "indienne", label: "Indienne" },
  { value: "indonesienne", label: "Indonésienne" },
  { value: "irakienne", label: "Irakienne" },
  { value: "iranienne", label: "Iranienne" },
  { value: "irlandaise", label: "Irlandaise" },
  { value: "islandaise", label: "Islandaise" },
  { value: "israelienne", label: "Israélienne" },
  { value: "italienne", label: "Italienne" },
  { value: "jamaicaine", label: "Jamaïcaine" },
  { value: "japonaise", label: "Japonaise" },
  { value: "jordanienne", label: "Jordanienne" },
  { value: "kazakhstanaise", label: "Kazakhstanaise" },
  { value: "kenyanne", label: "Kényane" },
  { value: "kirghize", label: "Kirghize" },
  { value: "kiribatienne", label: "Kiribatienne" },
  { value: "koweitienne", label: "Koweïtienne" },
  { value: "laotienne", label: "Laotienne" },
  { value: "lesothane", label: "Lesothane" },
  { value: "lettonne", label: "Lettonne" },
  { value: "libanaise", label: "Libanaise" },
  { value: "liberienne", label: "Libérienne" },
  { value: "libyenne", label: "Libyenne" },
  { value: "liechtensteinoise", label: "Liechtensteinoise" },
  { value: "lituanienne", label: "Lituanienne" },
  { value: "luxembourgeoise", label: "Luxembourgeoise" },
  { value: "macedonienne", label: "Macédonienne" },
  { value: "malgache", label: "Malgache" },
  { value: "malaisienne", label: "Malaisienne" },
  { value: "malawienne", label: "Malawienne" },
  { value: "maldivienne", label: "Maldivienne" },
  { value: "malienne", label: "Malienne" },
  { value: "maltaise", label: "Maltaise" },
  { value: "marocaine", label: "Marocaine" },
  { value: "marshallaise", label: "Marshallaise" },
  { value: "mauricienne", label: "Mauricienne" },
  { value: "mauritanienne", label: "Mauritanienne" },
  { value: "mexicaine", label: "Mexicaine" },
  { value: "micronesienne", label: "Micronésienne" },
  { value: "moldave", label: "Moldave" },
  { value: "monagique", label: "Monégasque" },
  { value: "mongole", label: "Mongole" },
  { value: "montenegrine", label: "Monténégrine" },
  { value: "mozambicaine", label: "Mozambicaine" },
  { value: "namibienne", label: "Namibienne" },
  { value: "nauruanne", label: "Nauruane" },
  { value: "nepalaise", label: "Népalaise" },
  { value: "nicaraguayenne", label: "Nicaraguayenne" },
  { value: "nigerienne", label: "Nigérienne" },
  { value: "nigeriane", label: "Nigériane" },
  { value: "norvegienne", label: "Norvégienne" },
  { value: "neo-zelandaise", label: "Néo-Zélandaise" },
  { value: "omanaise", label: "Omanaise" },
  { value: "ougandaise", label: "Ougandaise" },
  { value: "ouzbeke", label: "Ouzbèke" },
  { value: "pakistanaise", label: "Pakistanaise" },
  { value: "palauane", label: "Palaosienne" },
  { value: "palestinienne", label: "Palestinienne" },
  { value: "panameenne", label: "Panaméenne" },
  { value: "papouane-neo-guineenne", label: "Papouane-Néo-Guinéenne" },
  { value: "paraguayenne", label: "Paraguayenne" },
  { value: "neerlandaise", label: "Néerlandaise" },
  { value: "peruvienne", label: "Péruvienne" },
  { value: "philippine", label: "Philippine" },
  { value: "polonaise", label: "Polonaise" },
  { value: "portugaise", label: "Portugaise" },
  { value: "qatarienne", label: "Qatarienne" },
  { value: "roumaine", label: "Roumaine" },
  { value: "britannique", label: "Britannique" },
  { value: "russe", label: "Russe" },
  { value: "rwandaise", label: "Rwandaise" },
  { value: "saint-christopherienne", label: "Saint-Pattersonne / Kittitienne" },
  { value: "sainte-lucienne", label: "Sainte-Lucienne" },
  { value: "saint-marinaise", label: "Saint-Marinaise" },
  { value: "saint-vincentaise", label: "Saint-Vincentaise" },
  { value: "salomonaise", label: "Salomonaise" },
  { value: "salvadorienne", label: "Salvadorienne" },
  { value: "samoane", label: "Samoane" },
  { value: "sao-tomeenne", label: "Santoméenne" },
  { value: "senegalaise", label: "Sénégalaise" },
  { value: "serbe", label: "Serbe" },
  { value: "seychelloise", label: "Seychelloise" },
  { value: "sierra-leonaise", label: "Sierra-Léonaise" },
  { value: "singapourienne", label: "Singapourienne" },
  { value: "slovaque", label: "Slovaque" },
  { value: "slovene", label: "Slovène" },
  { value: "somalienne", label: "Somalienne" },
  { value: "soudanaise", label: "Soudanaise" },
  { value: "sud-soudanaise", label: "Sud-Soudanaise" },
  { value: "srilankaise", label: "Sri-Lankaise" },
  { value: "suedoise", label: "Suédoise" },
  { value: "suisse", label: "Suisse" },
  { value: "surinamaise", label: "Surinamaise" },
  { value: "swazie", label: "Eswatinienne" },
  { value: "syrienne", label: "Syrienne" },
  { value: "tadjikistanise", label: "Tadjike" },
  { value: "taiwanaise", label: "Taïwanaise" },
  { value: "tanzanienne", label: "Tanzanienne" },
  { value: "tchadienne", label: "Tchadienne" },
  { value: "tcheque", label: "Tchèque" },
  { value: "thailandaise", label: "Thaïlandaise" },
  { value: "timoraise", label: "East-Timoraise" },
  { value: "togolaise", label: "Togolaise" },
  { value: "tongienne", label: "Tongienne" },
  { value: "trinidadienne", label: "Trinidadienne" },
  { value: "tunisienne", label: "Tunisienne" },
  { value: "turkmene", label: "Turkmène" },
  { value: "turque", label: "Turque" },
  { value: "tuvaluane", label: "Tuvaluane" },
  { value: "ukrainienne", label: "Ukrainienne" },
  { value: "uruguayenne", label: "Uruguayenne" },
  { value: "vanuatuane", label: "Vanuatuane" },
  { value: "vaticane", label: "Vaticane" },
  { value: "vénézuélienne", label: "Vénézuélienne" },
  { value: "vietnamienne", label: "Yémenite" },
  { value: "zambienne", label: "Zambienne" },
  { value: "zimbabweenne", label: "Zimbabwéenne" },
];
const countries = [
  { value: "AF", label: "Afghanistan" },
  { value: "ZA", label: "Afrique du Sud" },
  { value: "AL", label: "Albanie" },
  { value: "DZ", label: "Algérie" },
  { value: "DE", label: "Allemagne" },
  { value: "AD", label: "Andorre" },
  { value: "AO", label: "Angola" },
  { value: "AG", label: "Antigua-et-Barbuda" },
  { value: "SA", label: "Arabie saoudite" },
  { value: "AR", label: "Argentine" },
  { value: "AM", label: "Arménie" },
  { value: "AU", label: "Australie" },
  { value: "AT", label: "Autriche" },
  { value: "AZ", label: "Azerbaïdjan" },
  { value: "BS", label: "Bahamas" },
  { value: "BH", label: "Bahreïn" },
  { value: "BD", label: "Bangladesh" },
  { value: "BB", label: "Barbade" },
  { value: "BE", label: "Belgique" },
  { value: "BZ", label: "Belize" },
  { value: "BJ", label: "Bénin" },
  { value: "BT", label: "Bhoutan" },
  { value: "BY", label: "Biélorussie" },
  { value: "MM", label: "Birmanie" },
  { value: "BO", label: "Bolivie" },
  { value: "BA", label: "Bosnie-Herzégovine" },
  { value: "BW", label: "Botswana" },
  { value: "BR", label: "Brésil" },
  { value: "BN", label: "Brunei" },
  { value: "BG", label: "Bulgarie" },
  { value: "BF", label: "Burkina Faso" },
  { value: "BI", label: "Burundi" },
  { value: "KH", label: "Cambodge" },
  { value: "CM", label: "Cameroun" },
  { value: "CA", label: "Canada" },
  { value: "CV", label: "Cap-Vert" },
  { value: "CL", label: "Chili" },
  { value: "CN", label: "Chine" },
  { value: "CY", label: "Chypre" },
  { value: "CO", label: "Colombie" },
  { value: "KM", label: "Comores" },
  { value: "CG", label: "Congo-Brazzaville" },
  { value: "CD", label: "Congo-Kinshasa" },
  { value: "KP", label: "Corée du Nord" },
  { value: "KR", label: "Corée du Sud" },
  { value: "CR", label: "Costa Rica" },
  { value: "CI", label: "Côte d'Ivoire" },
  { value: "HR", label: "Croatie" },
  { value: "CU", label: "Cuba" },
  { value: "DK", label: "Danemark" },
  { value: "DJ", label: "Djibouti" },
  { value: "DM", label: "Dominique" },
  { value: "EG", label: "Égypte" },
  { value: "AE", label: "Émirats arabes unis" },
  { value: "EC", label: "Équateur" },
  { value: "ER", label: "Érythrée" },
  { value: "ES", label: "Espagne" },
  { value: "EE", label: "Estonie" },
  { value: "SZ", label: "Eswatini" },
  { value: "US", label: "États-Unis" },
  { value: "ET", label: "Éthiopie" },
  { value: "FJ", label: "Fidji" },
  { value: "FI", label: "Finlande" },
  { value: "FR", label: "France" },
  { value: "GA", label: "Gabon" },
  { value: "GM", label: "Gambie" },
  { value: "GE", label: "Géorgie" },
  { value: "GH", label: "Ghana" },
  { value: "GR", label: "Grèce" },
  { value: "GD", label: "Grenade" },
  { value: "GT", label: "Guatemala" },
  { value: "GN", label: "Guinée" },
  { value: "GW", label: "Guinée-Bissau" },
  { value: "GQ", label: "Guinée équatoriale" },
  { value: "GY", label: "Guyana" },
  { value: "HT", label: "Haïti" },
  { value: "HN", label: "Honduras" },
  { value: "HU", label: "Hongrie" },
  { value: "IN", label: "Inde" },
  { value: "ID", label: "Indonésie" },
  { value: "IQ", label: "Irak" },
  { value: "IR", label: "Iran" },
  { value: "IE", label: "Irlande" },
  { value: "IS", label: "Islande" },
  { value: "IL", label: "Israël" },
  { value: "IT", label: "Italie" },
  { value: "JM", label: "Jamaïque" },
  { value: "JP", label: "Japon" },
  { value: "JO", label: "Jordanienne" },
  { value: "KZ", label: "Kazakhstan" },
  { value: "KE", label: "Kenya" },
  { value: "KG", label: "Kirghizistan" },
  { value: "KI", label: "Kiribati" },
  { value: "KW", label: "Koweït" },
  { value: "LA", label: "Laos" },
  { value: "LS", label: "Lesotho" },
  { value: "LV", label: "Lettonie" },
  { value: "LB", label: "Liban" },
  { value: "LR", label: "Libéria" },
  { value: "LY", label: "Libye" },
  { value: "LI", label: "Liechtenstein" },
  { value: "LT", label: "Lituanie" },
  { value: "LU", label: "Luxembourg" },
  { value: "MK", label: "Macédoine du Nord" },
  { value: "MG", label: "Madagascar" },
  { value: "MY", label: "Malaisie" },
  { value: "MW", label: "Malawi" },
  { value: "MV", label: "Maldives" },
  { value: "ML", label: "Mali" },
  { value: "MT", label: "Malte" },
  { value: "MA", label: "Maroc" },
  { value: "MU", label: "Maurice" },
  { value: "MR", label: "Mauritanie" },
  { value: "MX", label: "Mexique" },
  { value: "FM", label: "Micronésie" },
  { value: "MD", label: "Moldavie" },
  { value: "MC", label: "Monaco" },
  { value: "MN", label: "Mongolie" },
  { value: "ME", label: "Monténégro" },
  { value: "MZ", label: "Mozambique" },
  { value: "NA", label: "Namibie" },
  { value: "NR", label: "Nauru" },
  { value: "NP", label: "Népal" },
  { value: "NI", label: "Nicaragua" },
  { value: "NE", label: "Niger" },
  { value: "NG", label: "Nigéria" },
  { value: "NO", label: "Norvège" },
  { value: "NZ", label: "Nouvelle-Zélande" },
  { value: "OM", label: "Oman" },
  { value: "UG", label: "Ouganda" },
  { value: "UZ", label: "Ouzbékistan" },
  { value: "PK", label: "Pakistan" },
  { value: "PW", label: "Palaos" },
  { value: "PS", label: "Palestine" },
  { value: "PA", label: "Panama" },
  { value: "PG", label: "Papouasie-Nouvelle-Guinée" },
  { value: "PY", label: "Paraguay" },
  { value: "NL", label: "Pays-Bas" },
  { value: "PE", label: "Pérou" },
  { value: "PH", label: "Philippines" },
  { value: "PL", label: "Pologne" },
  { value: "PT", label: "Portugal" },
  { value: "QA", label: "Qatar" },
  { value: "CF", label: "République centrafricaine" },
  { value: "DO", label: "République dominicaine" },
  { value: "RO", label: "Roumanie" },
  { value: "GB", label: "Royaume-Uni" },
  { value: "RU", label: "Russie" },
  { value: "RW", label: "Rwanda" },
  { value: "KN", label: "Saint-Christophe-et-Niévès" },
  { value: "SM", label: "Saint-Marin" },
  { value: "VC", label: "Saint-Vincent-et-les-Grenadines" },
  { value: "LC", label: "Sainte-Lucie" },
  { value: "SB", label: "Îles Salomon" },
  { value: "WS", label: "Samoa" },
  { value: "ST", label: "Sao Tomé-et-Principe" },
  { value: "SN", label: "Sénégal" },
  { value: "RS", label: "Serbie" },
  { value: "SC", label: "Seychelles" },
  { value: "SL", label: "Sierra Leone" },
  { value: "SG", label: "Singapour" },
  { value: "SK", label: "Slovaquie" },
  { value: "SI", label: "Slovénie" },
  { value: "SO", label: "Somalie" },
  { value: "SD", label: "Soudan" },
  { value: "SS", label: "Soudan du Sud" },
  { value: "LK", label: "Sri Lanka" },
  { value: "SE", label: "Suède" },
  { value: "CH", label: "Suisse" },
  { value: "SR", label: "Suriname" },
  { value: "SY", label: "Syrie" },
  { value: "TJ", label: "Tadjikistan" },
  { value: "TW", label: "Taïwan" },
  { value: "TZ", label: "Tanzanie" },
  { value: "TD", label: "Tchad" },
  { value: "CZ", label: "Tchéquie" },
  { value: "TH", label: "Thaïlande" },
  { value: "TL", label: "Timor oriental" },
  { value: "TG", label: "Togo" },
  { value: "TO", label: "Tonga" },
  { value: "TT", label: "Trinité-et-Tobago" },
  { value: "TN", label: "Tunisie" },
  { value: "TM", label: "Turkménistan" },
  { value: "TR", label: "Turquie" },
  { value: "TV", label: "Tuvalu" },
  { value: "UA", label: "Ukraine" },
  { value: "UY", label: "Uruguay" },
  { value: "VU", label: "Vanuatu" },
  { value: "VA", label: "Vatican" },
  { value: "VE", label: "Venezuela" },
  { value: "VN", label: "Viêt Nam" },
  { value: "YE", label: "Yémen" },
  { value: "ZM", label: "Zambie" },
  { value: "ZW", label: "Zimbabwe" },
];
export {
  homeMetrics,
  homeMissions,
  projects,
  projectCategories,
  missions,
  qualities,
  metrics,
  investorSteps,
  entrepreneurSteps,
  faqs,
  project,
  nationalities,
  countries,
};
