const sectors = [
  "🌾 Agriculture & Agroalimentaire",
  "💅 Cosmétique & Soins Personnels",
  "⚡ Énergie & Énergies Renouvelables",
  "💻 Technologies & Innovation",
  "🎓 Éducation & Formation",
  "🏥 Santé, Bien-être & Esthétique",
  "👗 Mode, Beauté & Style",
  "🛍️ Commerce & Distribution",
  "🚚 Transport & Logistique",
  "🏗️ Immobilier & BTP",
  "🛠️ Artisanat & Industrie",
  "🌱 Environnement & Écologie",
  "💧 Eau & Assainissement",
  "🏦 Finance & Microfinance",
  "🎨 Art, Culture & Médias",
  "🏨 Tourisme & Hôtellerie",
  "🤝 Action Sociale & Communautaire",
  "🐟 Élevage & Pêche",
  "⛏️ Mines & Ressources Naturelles",
  "💼 Services aux Entreprises",
  "🌐 Autre",
];
export default sectors;
